### ISSUE TITLE
NameError: global name 'SEVENZIP' is not defined

### ISSUE THREAD

**Issue by vaneess** [clinton-hall/GetScripts#19]
i sometimes get the error from sabnzbd:
NameError: global name 'SEVENZIP' is not defined

7zip is installed, do i have to add a system variable?

**Comment by clinton-hall** [comment]
Can you show the logs?

**Comment by clinton-hall** [comment]
As a note here, these GetScripts are designed to work in NZBGet and not SABnzbd.

**Comment by vaneess** [comment]
hi clinton-hall
thank you for answering so quickly! :)
here are the logs, hope it helps

```
Script triggered from SABnzbd
Traceback (most recent call last):
File "C:\Program Files\SABnzbd\scripts\SAB-SafeRename.py", line 264, in <module>
rename_script(dirname)
File "C:\Program Files\SABnzbd\scripts\SAB-SafeRename.py", line 130, in rename_script
cmd = extract_command(shlex.split(line), dirname)
File "C:\Program Files\SABnzbd\scripts\SAB-SafeRename.py", line 212, in extract_command
if not os.path.exists(SEVENZIP):
NameError: global name 'SEVENZIP' is not defined
```

**Comment by vaneess** [comment]
thank youu! 👍 :)
